README.md
=> nathans Commit

script/landing.js
Creation of landing page JS file with page load function and fetch to NASA APOD API.
=> Initial landing js

README.md, landing.html
rough draft of landing html with foundation css framework
=> Landing html

assets/css/style.css
adding cs stylesheet and assets folder
=> adding css style sheet and assets folder

script/main.js
Added a function for fetching latitude and longitude from city input.
=> latitude_longitude_api

assets/script/main.js
Added function for fetching weather data.
=> added API for fetching weather data

assets/script/main.js, main.html
Added event listener for new input from user. Called the getLatLon() function in the event listener. Called the getWeatherData() in the getLatLon() function. Changed div to form in the main.html. Added ids in main.html. Changed button type to submit.
=> Added event listener for user city input

assets/css/style.css, main.html
adding forecast cards to main page html, update a few stylings in CSS
=> adding forecast cards, small update to css styling

assets/script/landing.js, landing.html
Updates landing JS file to match landing HTML file class names and fixes bugs in two event handlers in JS -- search button handler and image click handler.
=> Landing js match to html

assets/script/main.js, main.html
adds function to retrieve APOD data and loads image url into src attribute of img element.
=> Nasa apod feature

assets/css/style.css, assets/script/landing.js, assets/script/main.js, landing.html
added gradients to background and cards
=> css styling

assets/script/landing.js, landing.html
Fixed photo data generating bug.
=> fixed photo bug

landing.html
switching from foundation to bulma framework
search bar responsive
=> Landing framework

assets/css/style.css, main.html
=> feature match up commit

assets/script/main.js
Adds link to Nasa APOD image on main.html to redirect to Nasa APOD site
=> Link to apod

assets/script/main.js, main.html
Creates buttons to display searched cities and adds event listener to reload data on click.
=> Search history feature

assets/script/main.js
Added function in main.js for grabbing the user input from the landing page from the URL parameters.
=> Added function for grabbing user city input from landing page

assets/script/main.js
Reverts millersg47/StarParty#34
=> Revert "Added function for grabbing user city input from landing page"

assets/script/main.js, main.html
I started the function to load the date details. I adjusted some lines in the HTML to serve javascript purposes. I also noted similar data to use in the date details from the current date and future dates.
icon
clouds
night temperature
sunset
sunrise
moon phase
visible planets
=> started date details function and adjusted html for js purposes

assets/css/style.css
make background gradient cover page for landing html
=> Landing color

assets/css/style.css, landing.html, main.html
chose a google font, added color to the titles
=> Html font and color

main.html
=> responsiveness of cards on main page

main.html
responsiveness to rest of main.html
=> adding responsiveness

assets/css/style.css
=> viewport to fix background image

landing.html
=> landing html changes

landing.html, main.html
cleaning up lading page layout and responsiveness, also main page edits
=> Responsive html

assets/script/main.js
Adds function to fetch data from visible planets API based on user location input.
=> Fetches visible planet API data

assets/css/style.css, main.html
Added some lines to CSS (changed width %) and changed the bulma styling on HTML to be all same size.
=> make card size one line

assets/css/style.css, main.html
Added CSS class p100 for search bar size and .search-btn-container button for the Hx button size
=> made Hx button same size as search

assets/script/main.js, main.html
Added functions for loading main information.
loadWeatherDetails() loads weather information for current day.
loadPlanetDetails() loads visible planets for current day.
requestDay() returns the requested day. Can be used for loading information for the cards.
requestIcon() returns the weather icon. Can be used for loading icons for the cards.
=> Main weather and visible planet details

assets/css/style.css
=> fixing missing bracket

assets/css/style.css
fixxing image responsive issue adding .cards to the media screen
=> fixing image responsive issue

assets/css/style.css, assets/script/main.js
get planet icon and list styling
=> get visible object icon and styling

assets/script/main.js, main.html
new function added to populate forecast cards. Updates made to main.html and main.js
=> adds forecast data to cards

assets/script/main.js
list items under visibility won't duplicate when city is searched more than once
=> fixed duplicate list items

assets/script/main.js
Updates link to Nasa site to open in new tab.
=> changes image link to open new tab

assets/css/style.css, assets/script/main.js
added moon icons to main card and forecast cards
=> added moon icons

assets/script/landing.js, assets/script/main.js
Adds if statement to APOD fetch to load a preselected image if media type is video on both main and landing js files. 
Also adds new function to load the image info for the preselected photo in place of the video info on landing js file.
=> replaces video from APOD with photo

assets/script/main.js, main.html
Adds if statement inside getLatLon function to activate modal if user inputs an invalid city
=> modal load on invalid entry

assets/script/landing.js, assets/script/main.js, index.html
Adds geolocation fetch to landing page to check for valid city entry by user. If invalid, modal loads. If valid, user is redirected to search results.
=> invalid entry check added to landing.js

assets/css/style.css, index.html, main.html
changed the size of image at full hd to keep it from collapsing below other elements
=> fixes responsiveness of image on main page

assets/css/style.css, main.html
and styling to the text in cards, adds bottom margin of buttons to give spacing inbetween
=> text styling and button styling
